# dataset_name: "IMAplusplus"
new_dataset_metadata_output_dir: "../output/metadata/"
output_seg_masks_metadata_path: "IMAplusplus_seg_metadata.csv"
output_img_metadata_path: "IMAplusplus_img_metadata.csv"

# new_dataset_dir: "/local-scratch/localhome/kabhishe/WorkingDir/IMAplusplus_dataset/"
# new_dataset_masks_dir: "/local-scratch/localhome/kabhishe/WorkingDir/IMAplusplus_dataset/masks/"
# new_dataset_images_dir: "/local-scratch/localhome/kabhishe/WorkingDir/IMAplusplus_dataset/images/"
new_dataset_dir: "/dev/shm/myramdisk/IMAplusplus_dataset/"
new_dataset_masks_dir: "/dev/shm/myramdisk/IMAplusplus_dataset/masks/"
new_dataset_images_dir: "/dev/shm/myramdisk/IMAplusplus_dataset/images/"

output_seg_masks_metadata_qa_results_path: "IMAplusplus_seg_metadata_qa_results.csv"

verbose: true